services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_rest_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_rest
      SPRING_DATASOURCE_USERNAME: super
      SPRING_DATASOURCE_PASSWORD: tim123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_ENABLED: "true"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: bank_rest
      POSTGRES_USER: super
      POSTGRES_PASSWORD: tim123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U super -d bank_rest" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

#//docker exec -it postgres_db psql -U super -d bank_rest