#
# application.yml — главный конфигурационный файл Spring Boot.

server:
  port: 8080

spring:
  application:
    name: bank-card-management

  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: super
    password: tim123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
